services:
  - type: web
    name: metro-errands
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20.x
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /