services:
  - type: web
    name: metro-errands
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      # Server-side Supabase environment variables (recommended for API routes)
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
    autoDeploy: true
    healthCheckPath: /
